/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrameForm;

/**
 *
 * @author banhg
 */
import javax.swing.JFrame;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import Model.Student;
import DAO.StudentDao;
import DAO.ScoreDao;
import Model.Score;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

public class testChart extends javax.swing.JPanel {
    /**
     * Creates new form testChart
     */
    public testChart() {
        initComponents();
    }
     private static JFreeChart createChart(PieDataset dataset) {
        JFreeChart chart = ChartFactory.createPieChart(
                "CƠ CẤU TỶ LỆ XẾP LOẠI HỌC SINH", dataset, true, true, true);
        return chart;
    }

    private static PieDataset createDataset() throws Exception {
        ScoreDao dao = new ScoreDao();
        List<Score> list = dao.getScore();
        DefaultPieDataset dataset = new DefaultPieDataset();
        dataset.setValue("Học sinh giỏi",new Float(dao.getHSGioi()*10));
        dataset.setValue("Học sinh khá", new Float(dao.getHSKha()*10));
        dataset.setValue("Học sinh trung bình", new Float(dao.getHSTB()*10));
        dataset.setValue("Học sinh yếu", new Float(dao.getHSYeu()*10));

        return dataset;
    }
     public static void main(String[] args) throws Exception {
        JFreeChart pieChart = createChart(createDataset());
        ChartPanel chartPanel = new ChartPanel(pieChart);
        JFrame frame = new JFrame();
        frame.add(chartPanel);
        frame.setTitle("Biểu đồ JFreeChart trong Java Swing");
        frame.setSize(600, 400);
        frame.setLocationRelativeTo(null);
        frame.setResizable(false);
        frame.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
